### ISSUE TITLE
redis restart causes auth strategy issue

### ISSUE THREAD

**Issue by jamesdixon** [cilindrox/hapi-ioredis#4]
Hi, was curious if you've had this problem? https://github.com/hapijs/discuss/issues/248

It happens with both your library as well as the `hapi-redis` plugin.

Thanks!
James

**Comment by cilindrox** [comment]
@jamesdixon haven't run into it myself however, I'm usually a bit more explicit when setting up auth:

```js
// I use a 'true' value instead of 'required' in order to make it the default auth
server.auth.strategy('jwt', 'jwt', true, {});
```

Which version of Redis server are you testing this on?

**Comment by jamesdixon** [comment]
@cilindrox Redis version 3.0.7. That said, I believe this was just an issue caused by the plugin returning `next()` on every `ready` event, so I'll close this :)
